//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProdID { get; set; }
        public string ProdName { get; set; }
        public string Category { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string Logo { get; set; }
        public int CID { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
